project:
  type: website

website:
  title: "2026SpringIGERwebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ph01.qmd
      - ph02.qmd
      - ph03.qmd
      - ph04.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

